version: '3'

services:
  mediator:
    container_name: 'mediator'
    depends_on:
      - db
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_EXTERNAL_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src

  db:
    container_name: 'db'
    image: postgres:13.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
