version: '3'

services:
  mediator:
    container_name: 'mediator'
    env_file:
      - .env
    depends_on:
      - db
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_SHOW_SQL=false
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    networks:
      - internal

  db:
    container_name: 'db'
    image: postgres:13.1-alpine
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    name: internal