spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tictactoe
    username: postgres
    password: 1608
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    schemas: public
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB